### ISSUE TITLE
Has anyone realized every boss crashes? CFO,VP,CJ,CEO.

### ISSUE THREAD

**Issue by LittleNed** [ToontownStrideOfficial/ToontownStride#4]
after you finish killing the cfo or whatever, it says "The district has been reset to prevent a disconnect"

**Comment by LittleNed** [comment]
Cant even find the log, so :(

**Comment by LittleNed** [comment]
I am reading the black AI box, and it says a error about "toptoonsmgr"

**Comment by LittleNed** [comment]
Traceback (most recent call last):
  File "toontown\distributed\ToontownInternalRepository.py", line 69, in reader
ollOnce
    return AstronInternalRepository.readerPollOnce(self)
  File "C:\Panda3D-1.10.0\direct\distributed\ConnectionRepository.py", line 618
 in readerPollOnce
    if self.checkDatagram():
  File "C:\Panda3D-1.10.0\direct\distributed\DistributedObjectAI.py", line 548,
in setBarrierReady
    barrier.clear(avId)
  File "otp\ai\Barrier.py", line 57, in clear
    self.doneFunc(self.avIdList)
  File "C:\Panda3D-1.10.0\direct\showbase\PythonUtil.py", line 93, in _do__call
_
    return self._function(*(self._args + args), **_kargs)
  File "C:\Panda3D-1.10.0\direct\distributed\DistributedObjectAI.py", line 557,
in __barrierCallback
    callback(avIds)
  File "toontown\suit\DistributedSellbotBossAI.py", line 339, in __doneVictory
    self.d_setBattleExperience()
  File "toontown\suit\DistributedBossCogAI.py", line 158, in d_setBattleExperie
ce
    self.air.topToonsMgr.toonKilledBoss(toon, self.BossName)
AttributeError: 'ToontownAIRepository' object has no attribute 'topToonsMgr'

**Comment by craigy109** [comment]
Go through the code and remove top toons then?

not like you need it anyways Thats a simple fix
